const ICON_BASE_URL = '../assets/icon/';

export default {  
  personIcon: require(ICON_BASE_URL + 'Person.png'),
  keyIcon: require(ICON_BASE_URL + 'Key.png'),
  atSignIcon: require(ICON_BASE_URL + 'At_sign.png'),
  cloudIcon: require(ICON_BASE_URL + 'Cloud.png'),
  chevronRightIcon: require(ICON_BASE_URL + 'Chevron_Right.png'),
  documentIcon: require(ICON_BASE_URL + 'Document.png'),
  documentBlackIcon: require(ICON_BASE_URL + 'DocumentBlack.png'),
  doorIcon: require(ICON_BASE_URL + 'Door.png'),
  emailIcon: require(ICON_BASE_URL + 'Email.png'),
  exportIcon: require(ICON_BASE_URL + 'Export.png'),
  fingerprintIcon: require(ICON_BASE_URL + 'Fingerprint.png'),
  globeIcon: require(ICON_BASE_URL + 'Globe.png'),
  lockIcon: require(ICON_BASE_URL + 'Lock.png'),
  passportIcon: require(ICON_BASE_URL + 'Passport.png'),
  phoneIcon: require(ICON_BASE_URL + 'Phone.png'),
  menuIcon: require(ICON_BASE_URL + 'Menu.png'),
  searchIcon: require(ICON_BASE_URL + 'Search.png'),
  groupIcon: require(ICON_BASE_URL + 'People.png'),
  darkModeIcon: require(ICON_BASE_URL + 'Eclipse.png'),
  questionMarkIcon: require(ICON_BASE_URL + 'Question_Mark.png'),
  errorIcon: require(ICON_BASE_URL + 'Error.png'),
  warningShieldIcon: require(ICON_BASE_URL + 'Warning_Shield.png'),
  pencilIcon: require(ICON_BASE_URL + 'Pencil.png'),
  backIcon: require(ICON_BASE_URL + 'Back.png'),
  checkMarkIcon: require(ICON_BASE_URL + 'CheckMark.png'),
  personCircleIcon: require(ICON_BASE_URL + 'PersonCircle.png'),
  emailCheckMarkIcon: require(ICON_BASE_URL + 'EmailCheckMark.png'),
  typePasswordIcon: require(ICON_BASE_URL + 'TypePassword.png'),
  typeNewPasswordIcon: require(ICON_BASE_URL + 'TypeNewPassword.png'),
  reTypePasswordIcon: require(ICON_BASE_URL + 'ReTypePassword.png'),
  phoneRingCircleIcon: require(ICON_BASE_URL + 'PhoneRingCircle.png'),
  sendingEmailIcon: require(ICON_BASE_URL + 'SendingEmail.png'),
  sendMessageCursorIcon: require(ICON_BASE_URL + 'SendMessageCursor.png'),
  clockIcon: require(ICON_BASE_URL + 'Clock.png'),
  priceTagIcon: require(ICON_BASE_URL + 'PriceTag.png'),
  addKeyIcon: require(ICON_BASE_URL + 'AddKey.png'),
  birthdayCakeIcon: require(ICON_BASE_URL + 'BirthdayCake.png'),
  genderEqualityIcon: require(ICON_BASE_URL + 'GenderEquality.png'),
  trashCanIcon: require(ICON_BASE_URL + 'TrashCan.png'),
  laurelWreathIcon: require(ICON_BASE_URL + 'LaurelWreath.png'),
  leaderIcon: require(ICON_BASE_URL + 'Leader.png'),
  calendarIcon: require(ICON_BASE_URL + 'Calendar.png'),

  activeBellAlarm: require(ICON_BASE_URL + 'ActiveBellAlarm.png'),
  inactiveBellAlarm: require(ICON_BASE_URL + 'InactiveBellAlarm.png'),
  activeBlogSearchIcon: require(ICON_BASE_URL + 'ActiveGoogleBlogSearch.png'),
  inactiveBlogSearchIcon: require(ICON_BASE_URL + 'InactiveGoogleBlogSearch.png'),
  activeChatMessageIcon: require(ICON_BASE_URL + 'ActiveChatMessage.png'),
  inactiveChatMessageIcon: require(ICON_BASE_URL + 'InactiveChatMessage.png'),
  activeLikeIcon: require(ICON_BASE_URL + 'ActiveLike.png'),
  inactiveLikeIcon: require(ICON_BASE_URL + 'InactiveLike.png'),
  activeFAQIcon: require(ICON_BASE_URL + 'ActiveFAQ.png'),
  inactiveFAQIcon: require(ICON_BASE_URL + 'InactiveFAQ.png'),

  
  cancelCircleIcon: require(ICON_BASE_URL + 'CancelCircle.png'),
  cancelBlankIcon: require(ICON_BASE_URL + 'CancelBlank.png'),
  cancelBoxClearIcon: require(ICON_BASE_URL + 'CancelBoxClear.png'),
  cancelBoxBlackIcon: require(ICON_BASE_URL + 'CancelBoxBlack.png'),

  starSoftFilled: require(ICON_BASE_URL + 'StarSoftFilled.png'),
  starSoftEmpty: require(ICON_BASE_URL + 'StarSoftEmpty.png'),
  starSoftHalf: require(ICON_BASE_URL + 'StarSoftHalf.png'),
  starFilled: require(ICON_BASE_URL + 'StarFilled.png'),
  starEmpty: require(ICON_BASE_URL + 'StarEmpty.png'),
  starHalf: require(ICON_BASE_URL + 'StarHalf.png'),

  review0: require(ICON_BASE_URL + 'Review0.png'),
  review1: require(ICON_BASE_URL + 'Review1.png'),
  review2: require(ICON_BASE_URL + 'Review2.png'),
  review3: require(ICON_BASE_URL + 'Review3.png'),
  review4: require(ICON_BASE_URL + 'Review4.png'),
  review5: require(ICON_BASE_URL + 'Review5.png'),
};
